spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mwm_bd3?useSSL=false
    username: root
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false      
    #esta parte es para configurar el tamaño maximo de la imagen que se va subir.
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
     