spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mwm_bd2?useSSL=false
    username: root
    password: 123iscdv
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false      
  
     